### ISSUE TITLE
Recording path

### ISSUE THREAD

**Issue by bkj** [timtadh/zhang-shasha#24]
Is it possible to record the path of edits from one tree to another?  I'd like to be able to have a list of the operations that transforms tree A into tree B.  Is this included in the module at the moment, and if not could you point me towards a resource that might describe how to implement it?

Thanks!
Ben

**Comment by timtadh** [comment]
Hi Ben,

I have not had time to implement this feature as I have not needed it. It should be relatively straight forward to add path reconstruction, as is done for string edit distance, by recording the parent state on each modification. I have no current plans to implement path reconstruction as I have no need for it myself. However, I will gladly merge a PR.

-Tim

**Comment by timtadh** [comment]
you may find http://www.inf.unibz.it/dis/projects/tree-edit-distance/ useful.

**Comment by bkj** [comment]
Thanks for the quick reply.  On second thought, the algorithm might not be
appropriate for my application.  I was trying to come up with distance
metric on HTML DOM pages, but I see now that this algorithm only applies to
ordered labeled trees. In a DOM tree, you can't assume that the names of
the nodes are unique, as you might have something like

<body>
  <div>
    <span> ... </span>
  </div>
  <div>
    <table> ... </table>
  </div>
</body>

~ Ben

**Comment by timtadh** [comment]
Hi Ben,

Tree Edit Distance still applies. The labels do not need to be uniquely labelled, indeed they can all have the same label. The ordering means that there is an assumed order for the children of the node. This is usually easily achieved even in unordered trees.

-Tim

**Comment by bkj** [comment]
You mean by constructing some arbitrary order as long as it's consistent? (alphabetic by name, number of children, etc)?

**Comment by timtadh** [comment]
Yes. But that is not an issue for you as DOM trees are ordered labeled
trees. The ordering is by appearance in the html document.

Cheers
Tim Henderson

**Comment by bkj** [comment]
Gotcha -- thanks for your comments!

**Comment by timtadh** [comment]
ok. I am going to close this issue but feel free to open a PR or another issue if you have further problems.
