### ISSUE TITLE
Integrate TravisCI to ensure Python 2/3 compat

### ISSUE THREAD

**Issue by petrbel** [timtadh/zhang-shasha#28]
Hi, it would be great to use some kind of CI (eg. [TravisCI](https://travis-ci.org/), which is free for opensource projects). It runs all tests, builds etc. on each commit under different environments (such as python2.6, 2.7, 3.3, 3.4, 3.5 or idk what else). In addition, you can place some kind of icon into the readme in order to easily signal whether the tests passed or not.

**Comment by timtadh** [comment]
did this finally
