### ISSUE TITLE
pip3 error

### ISSUE THREAD

**Issue by borgr** [timtadh/zhang-shasha#29]
Hi, I am trying to install zss with pip3, but it throws out errors, am I not suppose to use pip for the python3 use as it is not implemented yet or something?

borgr@laptop:~/ucca$ pip3 install zss
Collecting zss
  Using cached zss-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aq965xju/zss/setup.py", line 3, in <module>
        import zss
      File "/tmp/pip-build-aq965xju/zss/zss/__init__.py", line 1, in <module>
        from compare import (
    ImportError: No module named 'compare'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aq965xju/zss/

**Comment by timtadh** [comment]
@borgr thanks for the bug report. I forgot to cut a new version and upload to pypi. That is now done. You should depend on 1.1.4 or greater. You will also need to install `numpy` and `editdist` separately if you want to take advantage of those speedups.
