### ISSUE TITLE
Nodes with same labels

### ISSUE THREAD

**Issue by afcruzs** [timtadh/zhang-shasha#31]
Hi,

I have some trees with the same label in some nodes, when I run the simple_distance method the whole program crashes. Does the distance function support repeated labels?. 

Thanks

**Comment by timtadh** [comment]
yes it support repeated labels. If you don't want to fix the bug yourself you are going to need to provide a lot more details.

**Comment by timtadh** [comment]
Closing this issue because there is not enough information to reproduce the problem.
