### ISSUE TITLE
How to specify the get_children() parameter in zss.distance()

### ISSUE THREAD

**Issue by yasodajayaweera** [timtadh/zhang-shasha#43]
I'm trying to compute the exact edit distance between two trees using the distance() function. Following is my code. I'm not sure how to specify the Node.get_children() parameter. Do I have to speicfy the children in only one tree or a particular node in one tree or all nodes in both trees?
```
# Tree 1
# a---> b
#  \--> c
c = Node('c', [])
b = Node('b', [])
a = Node('a', [b, c])

# Tree 2
# d---> b
#  \--> c
d = Node('d', [b, c])

x = distance(a, d, a.get_children(), insert_cost=2, remove_cost=2, update_cost=1)
print(x)
```

**Comment by timtadh** [comment]
Hi @yasodajayaweera ,

You probably want to use the `simple_distance` function unless you need to customize everything. Also, `insert_cost`, `remove_cost`, and `update_cost` are all functions.

For how to specify these functions (and the `get_children` function) see how it works in [simple_distance](https://github.com/timtadh/zhang-shasha/blob/master/zss/compare.py#L125). There is also fully worked example in the [README](https://github.com/timtadh/zhang-shasha#specifying-custom-tree-formats).

All the best,
Tim
