### ISSUE TITLE
Operation.__repr__ fails if nodes have no label attribute

### ISSUE THREAD

**Issue by smola** [timtadh/zhang-shasha#45]
When using custom nodes without a label attribute, Operation__repr__ will fail:

```
    def __repr__(self):
        if self.type == self.remove:
            return '<Operation Remove: ' + self.arg1.label + '>'
        elif self.type == self.insert:
            return '<Operation Insert: ' + self.arg2.label + '>'
        elif self.type == self.update:
>           return '<Operation Update: ' + self.arg1.label + ' to ' + self.arg2.label + '>'
E           AttributeError: 'Node' object has no attribute 'label'
```

**Comment by timtadh** [comment]
Ack. I think the `__repr__` should be used for those nodes to let them stringify themselves. What do you think? (Sorry for the slow response, I somehow missed this issue).

**Comment by smola** [comment]
@timtadh Yes, I think that would make sense. In my case I just got around the issue by not relying on Operation.__repr__ at all.

**Comment by BramVanroy** [comment]
I agree that printing operation is useful to get an idee what's being operated on. Perhaps it's better to just save the nodes themselves instead of their (possibly non-existant) `.label`.
