### ISSUE TITLE
Possible bug in zss 1.2

### ISSUE THREAD

**Issue by davide1995** [timtadh/zhang-shasha#46]
Hello,
First of all thank you for the development of this program.
I think I discovered a bug.
If you try to run this code you will receive an edit distance of 4.
```
from zss import simple_distance, Node

"""GRAPH: A"""
n1 = Node("f")
n2 = Node("a")
n3 = Node("h")
n4 = Node("c")
n5 = Node("l")
n6 = Node("e")

n1.addkid(n2)
n1.addkid(n6)
n2.addkid(n3)
n2.addkid(n4)
n4.addkid(n5)

A = n1

"""GRAPH: B"""
n10 = Node("f")
n11 = Node("a")
n12 = Node("d")
n13 = Node("e")
n14 = Node("c")
n15 = Node("b")

n11.addkid(n12)
n10.addkid(n13)
n14.addkid(n15)
n10.addkid(n11)
n11.addkid(n14)

B = n10

print(simple_distance(A, B))
```

But if you run this code you will receive an edit distance of 2.
```
from zss import simple_distance, Node

"""GRAPH: A"""
n1 = Node("f")
n2 = Node("a")
n3 = Node("h")
n4 = Node("c")
n5 = Node("l")
n6 = Node("e")

n1.addkid(n2)
n1.addkid(n6)
n2.addkid(n3)
n2.addkid(n4)
n4.addkid(n5)

A = n1

"""GRAPH: B"""
n10 = Node("f")
n11 = Node("a")
n12 = Node("d")
n13 = Node("e")
n14 = Node("c")
n15 = Node("b")


n10.addkid(n11)
n10.addkid(n13)
n11.addkid(n12)
n11.addkid(n14)
n14.addkid(n15)

B = n10

print(simple_distance(A, B))
```

The right one is the edit distance = 2. Just look to the attached image. What I changed is the order to attach a node to a node in the second tree and two nodes
![documento_2](https://user-images.githubusercontent.com/21131407/53289526-696f4500-3797-11e9-83e7-564ba1d5cdad.jpg)

**Comment by timtadh** [comment]
You have reversed the attachment order in you first example. You attach n11 after n13 to n10 in the first example but the other way around in the second example. Order matters in zhang-shasha.

**Comment by davide1995** [comment]
How can this make a difference? At the end we've always the same tree. Should the algorithm not working on the final tree?

**Comment by timtadh** [comment]
It makes a difference because the ordering of the children are reversed aka they are different trees. That is why the first example has a higher edit distance than the second.

**Comment by davide1995** [comment]
I still can't understand. See my image on the question. Both in the first and in the second method, the two generated trees are exactly the same. The algorithm should be independent on how the tree is constructed and which edge is added first and which after. It should look only at the final genersted tree otherwise... how can we get a reliable edit distance if this can change by the ordering of how I attach the edge zo the tree?

**Comment by timtadh** [comment]
your image is wrong. here are the corresponding images for your graphs. (produced using the dotty() command in my [betterast](https://github.com/timtadh/betterast) module).

![A1](https://user-images.githubusercontent.com/38620/53448171-a4f25500-39cb-11e9-9c3d-da8d02a5b40e.png)

![B1](https://user-images.githubusercontent.com/38620/53448177-a885dc00-39cb-11e9-9d09-779285f31398.png)

![A2](https://user-images.githubusercontent.com/38620/53448183-aae83600-39cb-11e9-95e3-4b702fe419dc.png)

![B2](https://user-images.githubusercontent.com/38620/53448193-af145380-39cb-11e9-8f98-79cee3a7de3d.png)

**Comment by davide1995** [comment]
Thank you so much for the picture. I thought the tree edit distance was independent if the node 'a' or the node 'e' was added first. Being these two nodes on the same level, I believed that the algorithm would have found the similarity between the two graphs in fewer steps

**Comment by timtadh** [comment]
this package only supports *ordered* tree edit distance. For unordered edit distance you will need to find a different algorithm. My suggestion is you canonicalize the ordering of the nodes by sorting them. That will allow you to use this algorithm.
