### ISSUE TITLE
Load tree from a string input

### ISSUE THREAD

**Issue by mahsa7823** [timtadh/zhang-shasha#52]
Hi. Thanks for the nice package. My input trees are stored in a text file, in the right format for the program (that is "Node("X").addkid(..."). Is there the code to load such input strings to the Node object? Thanks.

**Comment by timtadh** [comment]
Sounds like you put your trees in the format of python code. So just add `.py` to the file and import it. Otherwise my `betterast` package support serialization and deserialization: https://github.com/timtadh/betterast
