### ISSUE TITLE
Any idea to speed up the distance calculation

### ISSUE THREAD

**Issue by bdeng3** [timtadh/zhang-shasha#55]
Hey dev, 

Is there any way we could speed up the calculation? To be more specific, I got tens of thousands of trees who I wanted to compare with each other. Each tree has various number of nodes from less than a hundred to a few thousand.

I did some quick tests and found ZSS edit distance is quite useful. However currently I'm only utilizing the python "multiprocessing" library to speed up calculation. Is there other implementation such as tensorflow/pytorch that could utilize GOU power? Or other algorithm that's faster than ZSS?

**Comment by timtadh** [comment]
sounds like you have a research problem. I no longer do work in this space (and never did research just implemented an old algorithm). I recommend you read http://tree-edit-distance.dbresearch.uni-salzburg.at/ and the related work. Good luck.
